name: control
channels:
  - defaults
dependencies:
  - python=3.10.0
  - pip=24.2
  - pip:
      - audioread==3.0.1
      - face-alignment==1.4.1
      - librosa==0.10.2.post1
      - matplotlib==3.9.2
      - numpy==1.26.3
      - opencv-python==4.7.0.68
      - pillow==10.2.0
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - torch==2.3.1
      - torchaudio==2.3.1
      - torchvision==0.18.1
      - tqdm==4.66.5
      - transformers==4.45.2
